# Generated by Django 5.2.6 on 2025-09-26 05:52

import django.db.models.deletion
import product.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', validators=[product.validators.validate_file_size]),
        ),
    ]
